// auth (认证信息)
const SET_AUTH = 'SET_AUTH';
const CLEAR_AUTH = 'CLEAR_AUTH';

// breadcrumb 面包屑
const CHANGE_BREADCRUMB = 'CHANGE_BREADCRUMB';
const RESET_BREADCRUMB = 'RESET_BREADCRUMB';
const CLEAR_BREADCRUMB = 'CLEAR_BREADCRUMB';

// collapsed 导航菜单 状态
const CHANGE_COLLAPSED = 'CHANGE_COLLAPSED';
const CLEAR_COLLAPSED = 'CLEAR_COLLAPSED';

// menu 侧边导航栏
const MENU_OPENKEYS = 'MENU_OPENKEYS';
const MENU_SELECTKEYS = 'MENU_SELECTKEYS';
const CLEAR_MENU = 'CLEAR_MENU';

export {
  // authInfo
  SET_AUTH,
  CLEAR_AUTH,
  // breadcrumb
  CHANGE_BREADCRUMB,
  RESET_BREADCRUMB,
  CLEAR_BREADCRUMB,
  //collapsed
  CHANGE_COLLAPSED,
  CLEAR_COLLAPSED,
  // menu
  MENU_OPENKEYS,
  MENU_SELECTKEYS,
  CLEAR_MENU
};
